//
//  WelcomeRouter.swift
//  BankApp
//
//  Created by Anderson Lentz on 03/08/19.
//  Copyright (c) 2019 Anderson Lentz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol WelcomeRoutingLogic
{
  func routeStatements(segue: UIStoryboardSegue?)
}

protocol WelcomeDataPassing
{
  var dataStore: WelcomeDataStore? { get }
}

class WelcomeRouter: NSObject, WelcomeRoutingLogic, WelcomeDataPassing
{
  weak var viewController: WelcomeViewController?
  var dataStore: WelcomeDataStore?
  
  // MARK: Routing
    
    func routeStatements(segue: UIStoryboardSegue?) {
      if let segue = segue {
        let destinationVC = segue.destination as! StatementViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataStatement(source: dataStore!, destination: &destinationDS)
      }
      else {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "StatementViewController") as! StatementViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataStatement(source: dataStore!, destination: &destinationDS)
        navigateToStatements(source: viewController!, destination: destinationVC)
      }
    }
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
    
    func navigateToStatements(source: WelcomeViewController, destination: StatementViewController){
        source.show(destination, sender: nil)
    }
  
  //func navigateToSomewhere(source: WelcomeViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  func passDataStatement(source: WelcomeDataStore, destination: inout StatementDataStore)
  {
    destination.loggedUser = source.loggedUser
  }
}
