//
//  WelcomePresenter.swift
//  BankApp
//
//  Created by Anderson Lentz on 03/08/19.
//  Copyright (c) 2019 Anderson Lentz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WelcomePresentationLogic
{
  func presentLogin(response: Welcome.Login.Response)
}

class WelcomePresenter: WelcomePresentationLogic
{
  weak var viewController: WelcomeDisplayLogic?
  
  // MARK: Do something
  
  func presentLogin(response: Welcome.Login.Response)
  {
    let viewModel = Welcome.Login.ViewModel(success: response.success)
    viewController?.displayLogin(viewModel: viewModel)
  }
}
