//
//  AuthWorker.swift
//  BankApp
//
//  Created by Anderson Lentz on 03/08/19.
//  Copyright (c) 2019 Anderson Lentz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

class AuthWorker
{
    let users = ["ray": "secret"]
    
    func login(userID: String?, password: String?) -> (Bool,String)
    {
        
        let result:(Bool,String) = validatePassword(password: password)
        
        return result

    }
    
    func validateUser(user:String?){
        
    }
    
    
    func validatePassword(password: String?) -> (Bool,String) {
        
        if let password = password {
        
            let capitalLetterRegEx  = ".*[A-Z]+.*"
            let texttest = NSPredicate(format:"SELF MATCHES %@", capitalLetterRegEx)
            guard texttest.evaluate(with: password) else {
                return (false,"Password must have at leat one capital letter")
                
            }
            
            let numberRegEx  = ".*[0-9]+.*"
            let texttest1 = NSPredicate(format:"SELF MATCHES %@", numberRegEx)
            guard texttest1.evaluate(with: password) else {
                return (false,"Password must have at leat one number")
                
            }
            
            let specialCharacterRegEx  = ".*[!&^%$#@()/_*+-]+.*"
            let texttest2 = NSPredicate(format:"SELF MATCHES %@", specialCharacterRegEx)
            guard texttest2.evaluate(with: password) else {
                return (false,"Password must have at leat one special character")
                
            }
        }
        else{
            return (false,"Password is empty")
        }
        
        return (true,"OK")
    }
    
    func saveUserID(_ userID: Int?)
    {
        UserDefaults.standard.set(userID, forKey: "userID")
    }
    
    func getUserID() -> Int?
    {
        return UserDefaults.standard.integer(forKey: "userID")
    }
}
