//
//  AuthWorker.swift
//  BankApp
//
//  Created by Anderson Lentz on 03/08/19.
//  Copyright (c) 2019 Anderson Lentz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

class AuthWorker
{
    let users = ["ray": "secret"]
    
    func login(userID: String?, password: String?) -> Bool
    {
        guard let userID = userID, let password = password else { return false }
        return true
    }
    
    func saveUserID(_ userID: String?)
    {
        UserDefaults.standard.set(userID, forKey: "userID")
    }
    
    func getUserID() -> String?
    {
        return UserDefaults.standard.string(forKey: "userID")
    }
}
