//
//  WelcomePresenter.swift
//  BankApp
//
//  Created by Anderson Lentz on 03/08/19.
//  Copyright (c) 2019 Anderson Lentz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
    func presentStatements(response: Login.UserLogin.Response)
    func presentWarningMessage(response: Login.UserLogin.Response)
}

class LoginPresenter: LoginPresentationLogic
{
    
    
    
    
    weak var viewController: LoginDisplayLogic?
    
    // MARK: Do something
    
    func presentStatements(response: Login.UserLogin.Response)
    {
        if let user = response.loggedUser{
            let viewModel = Login.UserLogin.ViewModel(success: response.success, loggedUser: user)
            viewController?.displayStatements(viewModel: viewModel)
        }
        
    }
    
    func presentWarningMessage(response: Login.UserLogin.Response) {
        viewController?.displayWarningLoginMessage(response: response)
    }
}
