//
//  StatementRouter.swift
//  BankApp
//
//  Created by Anderson Lentz on 03/08/19.
//  Copyright (c) 2019 Anderson Lentz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol StatementRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol StatementDataPassing
{
  var dataStore: StatementDataStoreProtocol? { get }
}

class StatementRouter: NSObject, StatementRoutingLogic, StatementDataPassing
{
  weak var viewController: StatementViewController?
  var dataStore: StatementDataStoreProtocol?
  
  
}
